import Head from "next/head";
import { Box, ImageBox } from "../components/styled-components";
import { Hero, Activities, ShortGallery, Projects, References } from "../components";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Activities />
      <ShortGallery />
      <Projects />
      <References />
    </Box>
  );
}
